[build]
builder = "NIXPACKS"
buildCommand = "cd inventory-app && npm install && npm run build"
watchPatterns = ["inventory-app/**"]

[deploy]
startCommand = "cd inventory-app && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
